import type { Lesson } from './types/schedule';

export const lessons: Lesson[] = [
    {
        id: '1',
        dayOfWeek: 0,
        weekParity: "both",
        startTime: "9:50",
        endTime: "11:10",
        subject: "Основы права и права человека(л/пр)",
        room: '203/1',
    },
    {
        id: '2',
        dayOfWeek: 0,
        weekParity: 1,
        startTime: "11:20",
        endTime: "12:40",
        subject: "Статистика(л)",
        room: '418а/1',
    },
    {
        id: '3',
        dayOfWeek: 0,
        weekParity: 2,
        startTime: "11:20",
        endTime: "12:40",
        subject: "Психология управления(л)",
        room: '418а/1',
    },
    {
        id: '4',
        dayOfWeek: 0,
        weekParity: "both",
        startTime: "13:40",
        endTime: "15:00",
        subject: "Статистика(пр)",
        room: '130/1',
    },
    {
        id: '5',
        dayOfWeek: 0,
        weekParity: "both",
        startTime: "15:10",
        endTime: "16:30",
        subject: "БЖЧ(л)",
        room: '203/4',
    },
    {
        id: '6',
        dayOfWeek: 1,
        weekParity: "both",
        startTime:"9:50",
        endTime: "11:10",
        subject: "Макроэкономика(л)",
        room: '415/1',
    },
    {
        id: '7',
        dayOfWeek: 1,
        weekParity: "both",
        startTime:"11:20",
        endTime: "12:40",
        subject: "Культорология(л/сем)",
        room: '310/4',
    },
    {
        id: '8',
        dayOfWeek: 1,
        weekParity: "both",
        startTime:"13:40",
        endTime: "15:00",
        subject: "БЖЧ(пр)",
        room: '840/4',
    },
    {
        id: '9',
        dayOfWeek: 1,
        weekParity: "both",
        startTime:"15:00",
        endTime: "16:30",
        subject: "Физра",
        room: '3',
    },
    {
        id: '10',
        dayOfWeek: 2,
        weekParity: "both",
        startTime:"9:50",
        endTime: "11:10",
        subject: "Психология управления(пр)",
        room: '416/1',
    },
    {
        id: '11',
        dayOfWeek: 2,
        weekParity: "both",
        startTime:"11:20",
        endTime: "12:40",
        subject: "Управление организацией(л)",
        room: '418а/1',
    },
    {
        id: '12',
        dayOfWeek: 2,
        weekParity: "both",
        startTime:"13:40",
        endTime: "15:00",
        subject: "Экономика организации(л)",
        room: '234/1',
    },
    {
        id: '13',
        dayOfWeek: 3,
        weekParity: 'both',
        startTime:"8:15",
        endTime: "9:35",
        subject: "Маркетинг(л)",
        room: '421/1',
    },
    {
        id: '14',
        dayOfWeek: 3,
        weekParity: 'both',
        startTime:"9:50",
        endTime: "11:10",
        subject: "Макроэкономика(пр)",
        room: '325/1',
    },
    {
        id: '15',
        dayOfWeek: 3,
        weekParity: 1,
        startTime:"11:20",
        endTime: "12:40",
        subject: "Сетевые технологии(л)",
        room: '314/1',
    },
    {
        id: '16',
        dayOfWeek: 3,
        weekParity: 2,
        startTime:"11:20",
        endTime: "12:40",
        subject: "Маркетинг(пр)",
        room: '130/1',
    },
    {
        id: '17',
        dayOfWeek: 3,
        weekParity: "both",
        startTime:"13:40",
        endTime: "15:00",
        subject: "Физра",
        room: '3',
    },
    {
        id: '18',
        dayOfWeek: 4,
        weekParity: "both",
        startTime:"8:15",
        endTime: "9:50",
        subject: "Сетевые технологии(пр)",
        room: '135/1',
    },
    {
        id: '19',
        dayOfWeek: 4,
        weekParity: "both",
        startTime:"9:50",
        endTime: "11:10",
        subject: "Маркетинг(пр)",
        room: '318б/1',
    },
    {
        id: '20',
        dayOfWeek: 4,
        weekParity: "both",
        startTime:"11:20",
        endTime: "12:40",
        subject: "Управление организацией(пр)",
        room: '418а/1',
    },
    {
        id: '21',
        dayOfWeek: 4,
        weekParity: "both",
        startTime:"13:40",
        endTime: "15:00",
        subject: "Экономика организации(пр)",
        room: '412а/1',
    },
    {
        id: '22',
        dayOfWeek: 3,
        weekParity: "both",
        startTime:"16:40",
        endTime: "18:00",
        subject: "Экономика организации(пр)",
        room: '412а/1',
    },
]